spring:
  jpa:
    hibernate:
      ddl-auto: validate   # ?? ?? update / ??? validate ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  profiles:
    active: ${PROFILE:local}
  application:
    name: timely

server:
  forward-headers-strategy: framework

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: trace
